### PR TITLE
Add requirements section and edit build script

### PR DESCRIPTION
**Pull request by DerGoogler**
I've seen your app on TikTok. Really good project, but there are missing some things.

Most of your users come from TikTok and the most one have no clue what's a build script is or something to read the minimum required Android version. 

I added a requirement section to the `README.md` to clarify the user that he need minimum Android 8 (Oreo), if possible lower the requirement to reach more user on older devices.

> I recommend to match always the `compleSdk` with `targetSdk`.
> You also should increase the `versionCode` and `versionName` (if numeric) to prevent issues and make versioning best as possible

### CODE REVIEW

**Comment by ha2ked** [comment]
The minimum thing was is a brilliant idea i actuary suggest to him myself to do it

**Comment by ha2ked** [comment]
If you would like due to your contribution to the software help make a discord server for this repository

**Comment by DerGoogler** [comment]
> If you would like due to your contribution to the software help make a discord server for this repository and if so my [Discord](%5Bdiscord.com/users/993915202376572939)

We should wait for @simondankelmann's approval. If he/she don't want a Discord server then we need to mark it as **unofficial** Discord server.

**Review by simondankelmann — APPROVED** [review]
Thanks :)

**Comment by ha2ked** [comment]
> Thanks :)

So is that meaning  your good with the making of a server or are you thanking @DerGoogler

**Comment by DerGoogler** [comment]
@ha2ked I don't have that much experience with making a Discord server. I'm using Telegram for such things.

**Comment by simondankelmann** [comment]
Hi, i just wanted to thank for the pulm request, Ive sent you an email about the discord server ;) actually I am creating one right now

**Comment by ha2ked** [comment]
> > If you would like due to your contribution to the software help make a discord server for this repository and if so my [Discord](%5Bdiscord.com/users/993915202376572939)
> 
> We should wait for @simondankelmann's approval. If he/she don't want a Discord server then we need to mark it as **unofficial** Discord server.

Ok will look

**Comment by ha2ked** [comment]
> @ha2ked I don't have that much experience with making a Discord server. I'm using Telegram for such things.

Well even I you don't know how to make one I think it would be great if you helped out with issues on the server

**Comment by ha2ked** [comment]
Email sent

**Comment by DerGoogler** [comment]
> Email sent

You can add me via Discord (@Der_Googler)

**Pull request merged**
