### PR TITLE
Always build with your own signature

### PR DESCRIPTION
**Pull request by s1204IT**
Perhaps your intention is to always sign the same as the release.

By following these steps, you can always use release signatures to distribute APKs to your users:

1. Access [here](https://github.com/simondankelmann/Bluetooth-LE-Spam/settings/secrets/actions/new)
2. Create the following constants:
  - `STORE_FILE`: A Base64 encoded string of the signing key in JKS format
  - `STORE_PASSWORD`: Key store password
  - `KEY_ALIAS`: Key alias
  - `KEY_PASSWORD`: Key password
3. Run build!

By following these steps, you can work safely without revealing your signature or password to anyone other than yourself.

Be sure to create constants for Secrets before merging.

### CODE REVIEW

**Comment by s1204IT** [comment]
Currently, the build is failing in your repository, which is understandable because you are changing the virtual machine variables.

**Review by simondankelmann — APPROVED** [review]

**Review by simondankelmann — APPROVED** [review]

**Comment by simondankelmann** [comment]
Very nice, thank you. I followed your instructions but somehow there is still an issue with the signing. it says the store password is incorrect. i double checked it. locally i base64 encoded my jks file and reversed it to jks again with the command you provided in the workflow. after that i can use it with my password and create the signed apk's locally. on github somehow it fails

**Comment by s1204IT** [comment]
Ok, I'll deal with failure.

**Comment by s1204IT** [comment]
I created a JKS using Android testkey myself and verified it with it.

`STORE_FILE`:
<details>

```sh
$ cat sign/android.jks | base64
```
```
MIIL5gIBAzCCC5AGCSqGSIb3DQEHAaCCC4EEggt9MIILeTCCBbAGCSqGSIb3DQEHAaCCBaEEggWd
MIIFmTCCBZUGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUM
MCsEFDkVWLeEI7S7enUTBtvatqtAYFfPAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQB
KgQQnMNXrImqdTJT8pgJ2BdWngSCBNClzy82JHrogW8RsJd3gHKSz8sfS5mYmgYLRyzThzfq2Erm
XcgUGvhnzHD6LZ9yhnqX+2YCU2ZMM5TMlutmJLtocz4qa9mct+8evivMa+Le28Ik1OGY0v36wXdZ
M+rlAOqyu2+YfB8kRhB5LMaE8Bu6ZEDQE+2pLIsCn2UuMLuwjAxo6Pv2q+uy5TKNr3VrIQfZQDh9
jlgy8ulimwCNh0wlmU+aXA4sTHmczwKsWaqynBes+98I+ou/wWha7fbQNMIC2k28vFHmvR6oWjJ7
nDk6IuR43R4h4ySPHzZ23cyq9eneh5DNbt25F3ElsKMW2NwUZBPYUfFb9FfWYVj9aqHl3kYr6rqk
dKV0J1GjcmX7JNmInGMjm//eh9qsVsn7C4CbfuCJbDFBHKbNx+YJUFjuiz4ninLH9wsWATFtAXhu
8/b77G3H4B84zYmIe6BWV4wlkmvKwm3tpKPoi6IWiZAmVT103/z3W45LdcTSvmLER2oqbxh3xIJS
l8m4yfMXvVQnqPkqHfLboFBVDkPat4RyHo668VWjf+qAYdQLwEf36YhQHzvru/oa36UKUJLc6Oap
MaWiOwBLbgflPGd3wRlcIpr7IkgJLw6Dv4Aj9A+lzFuBqs5YUm2OBTgS/wHLRLRyHvmXnACTvwzD
Q03qV5Cou80ZZqThHT0jiN60dB/eIvvY4aHOX/PYXxC1HqufFzFiAY67G/VJNA6Lci6dDzitMQVu
MrkCVldWeOFsYdrsDVHL3tpuxka0oJjd5Td4BUiEOLf3kQAEXW8UvRlwdnaWdsfCGwHkofBXWLVV
5e1V4f3el+4Z6FISQcnOSbg2JSGe6q3cDH8wRWZ/RoLgWY3bUBPrwCb7zo5OrGEAkYlLOjgVrCIp
RZ1Lp6s0h3XKODL+UvP8J4ZLmnn00gX75Nps7Y4/xM6Cdda2c8hlfNzCILBCWGeEyd/XKsFa8krh
Uyj1g0e13z9PvXh9c2HizVxiRlS6RjTxTGXnKJuZXA7b/RHImiB0J72aujZB3sO8u48dkUsBurEp
qdDXHBxz1zfOs/BDD+IxyLOZwdhRRpOP2ETWSzk+CyjpSJBuAA4PM1sgg1R7XN5ScvYMRq+/EGv8
RWJed3UBGhllyEAlYQAsTRHu82LkwEDd7mYWXONcj866tIc3j5FczXZRkF2MciuOmzGBWIbs/htf
rpHLrUbz9oOFvQ8SDbjidCpvtUGlRNfMJlq97FIw6ad6mSwkWY3rY0P32pnm0yZJ5MbIaHeoFSoO
LDRMetpYJN/TImpIhGCGL8rq5WWZHdkx88c7rJ7tHqVpxo+b2DvixC/FEr9uG1PmG9p8BzdlMr1x
+CpUHxjzGv98OdM+ruIdNj2IwhVb2VaduNSPDBhLzcEoNQL+OY4sccTQrDQxbcGp6/h6Fg1F5P15
SlQGIR5iIrbC/5DGs6DSpttnB05Kl0ZKaXS+ESPWQRRcLkidpyBwSITMrSplhz7jyf4dKlvsOjdC
z2KUcl9dh2nIWD3kmXQ2+0na61BpN4QBa3ZdqO3MwRS6hnT7VZQZy3K0vBqwloHec2pufMhaG5r1
Twx9pLClzUTjEn7FxDIL7NsXIbjzr9bxuoovjp+z8k+J/HeExI/ykRrd6DQ0lUShrFLhO/P1zivw
cjFCMB0GCSqGSIb3DQEJFDEQHg4AYQBuAGQAcgBvAGkAZDAhBgkqhkiG9w0BCRUxFAQSVGltZSAx
Njc4MDY5NDEwNDI2MIIFwQYJKoZIhvcNAQcGoIIFsjCCBa4CAQAwggWnBgkqhkiG9w0BBwEwZgYJ
KoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFFczXfcRqHYoDhHhfqnT37AHpYd5AgInEAIBIDAM
BggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQAX0p/8+AMXre9kdwC44B1ICCBTCl4fHbJT38WzHn
+DXPXK9l+e31M5zAe8oJnRlJHI4F1SGKeViHkQupqjejyjP8zg0BSbKNmDjewahBnGh+l1ulH595
k8qImsf8QLtW4SQ5gqvrUgkHTskcqR939P9UbqW1fV+DQxJlBElvblttEYKf3lII5N1lt7rxbVuv
fkEl66PH4bq0gIKk3+SbkW827YWWmjdDfPtk3c8E3B2Qdky3M8ZSRSSQzPrW0OG6TcuaOJ/tJtCn
KH7TcnhmPBPzbiAsLeX3hOh+APPa064tOJAv3c/9aJHf1lE9rNoOckzIWlO6PEWad482M7NkfMZR
qrssqbGBLBrQhBU8GF9kkJw/HWZD3nOXLDEq7t4IKIbK3MyR0HVsTXyWGS6K1179mYbKpXsXe604
IfTRQyFNIxEIoxJNb0DZsgBoXGV6LtHEAstGDdRyHev1j1cCKcGMriFlb9jjkt8vpRGOe5kPhBJE
tIUnsZ9Y/mfDJ87vMfk8xP+w2+t7nlWCzFFSLpmE6FxXo/eUO7lMPbDj5679sv/KvUe+ysCSsMl5
OrmG8GXGO4jpGXzJDyxNRmckuOCWKMvqzsu8Ndp05V+Qn2QAZecuRgD9fErBkspI4IhY/oG3K3aI
OfWQENiQSvEZ32O3E85Can3hBwhRXqfnUH6r+axNIP3KFI8uasdK9toezdUW4rgEX6NYr6nnZSyA
APVghxOAs8p+MGpVXHJ3R+pMCEk09Bc1XjPdIZPeUks9Z48lpgq+0MxCtKnImLO6EHSnOdaOg/p7
aJGQtmOeiesV5eSslGqSSwwh4SX0MQJXYw24wciI9kxDekS5dE4oe3+xJ7OUzL/lASJQu3v/fvR+
1yySnXS/OKp5Lq09hMzAQef86tbvy8+qG7ZNoPYvqQObW6cyowOz5r1FMvHFLWKlyGpsjHQisR2K
QzDwSxnmEgBlN6CSidoOBiEbZIUeaOJZSKuQCK2RvH7+r+xOWx4d9iLq+FMZgzyqOpcwqEEo4Fo8
OxleYEgMLz1YOZZQjg8th9wbkNueXeQq2y8WTlqGTtUiRCtVjDfr/dSFc/ueN749XamlogPYCXWe
v3H5RF7AjFK2ovlQm+Kos44g4HSbpQL/48nWtRidWAEzMySvooeTzLmZ8RvuMeb/7M5e0AuOgjPM
cIuCumgGYA9e/GmVEh2NuPsIOFYTxOnVjZLBzGQGzKLiz7aD1XvNJ6CzMomrbU3GLgJwM89+cxRW
xq8P2iQmmq6jcd4WXUXwvoh+vuZ0scMD6sh7uP0wpDhBEFdef5GOS6jbVbN9KRVOHJ74H8v2jJda
jNvWePJa0v9TMyOpYX7x0Wv55oOcuIt1HEOUS3Y38LRkmNlhGiGbT/JICIG/JX/nieESRGHJELnW
lxFASSK3n/szh5X/ApV8W9bgzCfj7p/ZrL52GRgRDIbu42S6F2kOaNNv5kw+dNeGPqLhs2GFjdQq
zIN+sEwHO1sUCOm52HhpD/LuZ1C2DRbTB4P2aErhG0851J3hlFGyygdIommCgpBVKejwCm3AjGC+
6LxxZNmAUHtFs3Ht9BS8EPoLvqs8K5iHzih0xv+pxBTUFVJQKgPRIM1XJZb4iUMKJ+//ocQHmNit
vI8JtStKGAoN5uT/S1EduKXEoPWZCXuWuS+lZqjBIoJPTvMo7KAWzgt7dfEEeM7T20LIo1BLrVFY
rUCN0AaCGv90NxJ1XdbGTElMVuXhPkzyEpbySWpS7Dg8IsZTVirYDcpM3dhWiBdSxEv4Yxo28kOx
4pF4DvU6gDBNMDEwDQYJYIZIAWUDBAIBBQAEIKhKzyNjsbfBotMc0XaD/woi0wWPjAplm65z0zue
ZG+IBBTrT9C4ZHmse1P6Uworue5tiPNRGQICJxA=
```
</details>

`STORE_PASSWORD`: `android`
`KEY_ALIAS`: `android`
`KEY_PASSWORD`: `android`

**Comment by s1204IT** [comment]
```sh
keytool -list -v -keystore keystore.jks
```
Please verify that the following command can be executed.

---

<details><summary>Example output</summary>

```
Enter keystore password:
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 1 entry

Alias name: android
Creation date: Mar 6, 2023
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
Issuer: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
Serial number: 936eacbe07f201df
Valid from: Fri Feb 29 10:33:46 JST 2008 until: Tue Jul 17 10:33:46 JST 2035
Certificate fingerprints:
         SHA1: 61:ED:37:7E:85:D3:86:A8:DF:EE:6B:86:4B:D8:5B:0B:FA:A5:AF:81
         SHA256: A4:0D:A8:0A:59:D1:70:CA:A9:50:CF:15:C1:8C:45:4D:47:A3:9B:26:98:9D:8B:64:0E:CD:74:5B:A7:1B:F5:DC
Signature algorithm name: SHA1withRSA (weak)
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions:

#1: ObjectId: 2.5.29.35 Criticality=false
AuthorityKeyIdentifier [
KeyIdentifier [
0000: 48 59 00 56 3D 27 2C 46   AE 11 86 05 A4 74 19 AC  HY.V=',F.....t..
0010: 09 CA 8C 11                                        ....
]
[EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US]
SerialNumber: [    936eacbe 07f201df]
]

#2: ObjectId: 2.5.29.19 Criticality=false
BasicConstraints:[
  CA:true
  PathLen: no limit
]

#3: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 48 59 00 56 3D 27 2C 46   AE 11 86 05 A4 74 19 AC  HY.V=',F.....t..
0010: 09 CA 8C 11                                        ....
]
]



*******************************************
*******************************************



Warning:
<android> uses the SHA1withRSA signature algorithm which is considered a security risk. This algorithm will be disabled in a future update.
```
</details>
You can also check alias by adding the `-v` option.

**Comment by simondankelmann** [comment]
i created a new keystore for that purpose and it seems to work locally with the keytool but once i insert the secrets in guthub, the build fails because of wrong password somehow

**Comment by s1204IT** [comment]
hmm...

Does your keystore password contain **symbols**?

**Comment by simondankelmann** [comment]
yep, that was the problem. I created one more without symbols, no it works. thank you very much !

**Pull request merged**
